name: Test & Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Only runs when pushing a version tag like v0.1.0

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest

  publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    needs: test   # ✅ This ensures it only runs if 'test' passes!

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies (without installing project itself)
        run: poetry install --no-root

      - name: Build & Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build
