name: Test & Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Only runs when pushing a version tag like v0.1.0

jobs:
  test:
    name: Run tests with coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=your_package_name --cov-report=xml

      # OPTIONAL: Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
        # Remove this step if you don't use Codecov

  publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    needs: test  # ✅ Will only run if tests pass

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies (without installing project itself)
        run: poetry install --no-root

      - name: Build & Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build
